### ISSUE TITLE
Add routing system to dummy maps using dummy data for now.

### ISSUE THREAD

**Issue by Trisanu-007** [VikrantReddy/Traffic-management-and-simulation#4]
Use and make a routing data using dummy traffic densities for now

**Comment by Trisanu-007** [comment]
Please review @VikrantReddy @Nikhil-Vaddipati

**Comment by VikrantReddy** [comment]
@Trisanu-007 Could you please name the nodes for easier usage?

**Comment by VikrantReddy** [comment]
Duplicate of #3
